package io.github.kuberatest.util.message;

public enum MessageKey {
    TAG_TEXTBOX,

    INFO_SKIP,

    FAIL_MESSAGE_FORMAT,
    FAIL_ELEMENT_CHECK_CONDITION_NOT_MATCH,
    FAIL_ELEMENT_VALUE_CONDITION_NOT_MATCH,
    FAIL_NO_SUCH_WINDOW_TITLE,

    ERROR_ROW_START_NOT_FOUND,
    ERROR_TEST_CASE_NAME_NOT_FOUND,

    PARAM_CONDITION_CHECKED,
    PARAM_CONDITION_UNCHECKED,
    PARAM_CONDITION_UNSELECTED
}
